name: Template Sync

on:
  # cronjob trigger
  # schedule:
  # - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:


jobs:
  repo-sync:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@main
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@main
        with:
          source_repo_path: ScoopInstaller/BucketTemplate
          upstream_branch: master
          pr_labels: template_sync
