name: Template Sync

on:
  # cronjob trigger
  # schedule:
  # - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:


jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: ScoopInstaller/BucketTemplate
          upstream_branch: master
